apiVersion: apps/v1
kind: Deployment 
metadata:
  name: bkacad-hello-world
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: bkacad-hello-world
  template:
    metadata:
      labels:
        app: bkacad-hello-world
    spec:
      containers:
      - image: anhnbt/node-hello-world-bkacad-anhnbt:latest
        name: bkacad-hello-world
        ports:
          - containerPort: 8080
