Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: "echo A"

    config.vm.define "master" do |master|
        master.vm.box = "centos/7"
        master.vm.hostname = "k8s-master"
        master.vm.network "private_network", ip: "192.168.50.4"
        master.vm.provider "virtualbox" do |v|
            v.name = "my_vm_master"
            v.memory = 2048
            v.cpus = 2
        end
    end

    config.vm.define "worker" do |worker|
        worker.vm.box = "centos/7"
        worker.vm.hostname = "k8s-worker"
        worker.vm.network "private_network", ip: "192.168.50.5"
        worker.vm.provider "virtualbox" do |v|
            v.name = "my_vm_worker"
            v.memory = 2048
            v.cpus = 2
        end
    end

    config.vm.provision :shell, inline: "echo C"
end